source "https://rubygems.org"
gem 'sinatra'
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter', '~> 3.1.0'
gem 'sinatra-contrib', '~> 3.0', '>= 3.0.5'
gem 'cors'
gem 'activesupport'
gem 'activerecord'
gem 'rake'
gem 'sqlite3'
